# Generated by Django 2.2.1 on 2019-09-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='contact',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='designation',
            field=models.CharField(default='doctor', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='field',
            field=models.CharField(choices=[('OPD', 'OPD'), ('orthopedia', 'orthopedia'), ('Pediatric', 'Pediatric'), ('Cardiologist', 'Cardiologist'), ('Gyanecologist', 'Gyanecologist')], default='inprocess', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofileinfo2',
            name='contact',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo2',
            name='designation',
            field=models.CharField(default='patient', max_length=10),
        ),
    ]
