# Generated by Django 2.2.1 on 2019-09-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0002_auto_20190917_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='appointday',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='monday', max_length=20),
        ),
    ]
