# Generated by Django 2.2.1 on 2019-09-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0003_auto_20190917_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('inprocess', 'inprocess'), ('accepted', 'accepted'), ('complete', 'complete')], default='inprocess', max_length=30),
        ),
    ]
