# Generated by Django 2.2.5 on 2019-09-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0004_auto_20190918_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
